<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ik</string>
	</array>
	<key>firstLineMatch</key>
	<string>^#!/.*\bioke\b</string>
	<key>foldingStartMarker</key>
	<string>(method|do|macro|fn|fnx|describe|it)\((?![^)]*+\))</string>
	<key>foldingStopMarker</key>
	<string>^\s*+\)</string>
	<key>name</key>
	<string>Ioke</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>[[:alnum:]!?_:-]+(?=[[:space:]]*=.*mimic.*($|\.))</string>
			<key>end</key>
			<string>(?=\.)|$</string>
			<key>name</key>
			<string>constant.object.mimic.ioke</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#operator_symbols</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator_names</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#kinds</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prototype_names</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#operator_symbols</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operator_names</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#kinds</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#prototype_names</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>;</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.ioke</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[[:digit:]_.eE\-]+\b</string>
			<key>name</key>
			<string>constant.numeric.ioke</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b0[xX][A-Fa-f0-9]+</string>
			<key>name</key>
			<string>constant.numeric.hexadecimal.ioke</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[A-Z][[:alnum:]!?_:-]*\b</string>
			<key>name</key>
			<string>constant.kind.ioke</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[[:alnum:]!?_:-]+(?=[[:space:]]*[+*/-]?=[^=].*($|\.))</string>
			<key>name</key>
			<string>variable.assignment.ioke</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[[:alnum:]!?_:-]+?:\s</string>
			<key>name</key>
			<string>string.literal.keyword-argument.ioke</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[^[:alnum:]!?_:-]:[[:alnum:]!?_:-]+</string>
			<key>name</key>
			<string>string.literal.symbol.ioke</string>
		</dict>
		<dict>
			<key>match</key>
			<string>:"[[:alnum:][:space:]\\!?_:-]*"</string>
			<key>name</key>
			<string>string.literal.symbol.ioke</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#/.*?/[oxpniums]*</string>
			<key>name</key>
			<string>string.regexp.ioke</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#r\[.*?\][oxpniums]*</string>
			<key>name</key>
			<string>string.regexp.ioke</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.ioke</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.ioke</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.ioke</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>source.embedded.empty.ioke</string>
						</dict>
					</dict>
					<key>match</key>
					<string>#\{(\})</string>
					<key>name</key>
					<string>source.embedded.ioke</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>#\{</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.ioke</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>source.embedded.ioke</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#nest_curly_and_self</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>#\[</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>string.quoted.double.ioke</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.ioke</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.ioke</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>source.embedded.empty.ioke</string>
						</dict>
					</dict>
					<key>match</key>
					<string>#\{(\})</string>
					<key>name</key>
					<string>source.embedded.ioke</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>#\{</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.ioke</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>source.embedded.ioke</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#nest_curly_and_self</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(fn|fnx|method|macro)\b</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Base|DefaultBehavior|Ground|Origin|System|Runtime|Text|Number|Method|DefaultMethod|JavaMethod|Mixins|Restart|List|Dict)\b</string>
			<key>name</key>
			<string>entity.prototype-names.ioke</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(print|println|cell|documentation|while|until|asText|inspect|loop|bind|restart|do|true\?|false\?|nil\?|call|list|dict|empty\?|with|set)\b</string>
			<key>name</key>
			<string>keyword.cell-names.ioke</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\`|\.|\,|@|@@|\(|\))</string>
			<key>name</key>
			<string>punctuation.ioke</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bit\b</string>
			<key>name</key>
			<string>entity.standout-names.ioke</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(return|break|mimic|self|use|if|unless|true|false|nil)\b</string>
			<key>name</key>
			<string>keyword.operator.names.ioke</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>kinds</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b[A-Z][[:alnum:]!?_:-]*\b</string>
					<key>name</key>
					<string>constant.kind.ioke</string>
				</dict>
			</array>
		</dict>
		<key>nest_curly_and_self</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.scope.ioke</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#nest_curly_and_self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>operator_names</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(return|break|mimic|self|use|if|unless|true|false|nil)\b</string>
					<key>name</key>
					<string>keyword.operator.names.ioke</string>
				</dict>
			</array>
		</dict>
		<key>operator_symbols</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(=~|!~|\.\.\.|=&gt;|\+\+|\-\-|\*|\/|%|\+|\-|&lt;&lt;|&gt;&gt;|&gt;|&lt;|&lt;=|&gt;=|&lt;=&gt;|==|!=|&amp;|\^|\||&amp;&amp;|\|\||\.\.|=|\+=|\-=|\*=|\/=|%=|&amp;=|\^=|\|=|&lt;&lt;=|&gt;&gt;=|&lt;\-|&lt;\-&gt;|\-&gt;)</string>
					<key>name</key>
					<string>entity.operator.symbols.ioke</string>
				</dict>
			</array>
		</dict>
		<key>prototype_names</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(Base|DefaultBehavior|Ground|Origin|System|Runtime|Text|Number|Method|DefaultMethod|JavaMethod|Mixins|Restart|List|Dict)\b</string>
					<key>name</key>
					<string>entity.prototype-names.ioke</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ioke</string>
	<key>uuid</key>
	<string>EC751C80-9E93-44B4-AFF3-EF4FF8346C90</string>
</dict>
</plist>
