<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ik</string>
	</array>
	<key>firstLineMatch</key>
	<string>^#!/.*\bioke\b</string>
	<key>keyEquivalent</key>
	<string>^~I</string>
	<key>name</key>
	<string>Ioke</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>;</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.ioke</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>#!</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.ioke</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>((?&lt;=fn\()|(?&lt;=fnx\()|(?&lt;=method\()|(?&lt;=macro\()|(?&lt;=lecro\()|(?&lt;=syntax\()|(?&lt;=dmacro\()|(?&lt;=dlecro\()|(?&lt;=dlecrox\()|(?&lt;=dsyntax\())[[:space]]*"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.documentation.ioke</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#text_literal_escapes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_source</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>((?&lt;![[:alnum:]!?_:])|(?&lt;![[:alnum:]!?_:]!))[[:alnum:]!?_]+:\s</string>
			<key>name</key>
			<string>string.literal.keyword-argument.ioke</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[[:alnum:]_:][[:alnum:]!?_:]*(?=[[:space:]]*[+*/-]?=[^=].*($|\.))</string>
			<key>name</key>
			<string>variable.assignment.ioke</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#assignments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#kinds</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((?&lt;![[:alnum:]!?_:])|(?&lt;![[:alnum:]!?_:]!))[[:alnum:]!?_:]+(?=[[:space:]]*=.*mimic[[:space]])</string>
			<key>name</key>
			<string>constant.object.mimic.ioke</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![[:alnum:]])[+-]?[[:digit:]][[:digit:]]*(\.[[:digit:]])?[[:digit:]]*([eE][+-]?[[:digit:]]+)?(?![[:alnum:]!?_:])</string>
			<key>name</key>
			<string>constant.numeric.ioke</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((?&lt;![[:alnum:]!?_:])|(?&lt;![[:alnum:]!?_:]!))0[xX][[:xdigit:]]+\b</string>
			<key>name</key>
			<string>constant.numeric.hexadecimal.ioke</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((?&lt;![[:alnum:]!?_:])|(?&lt;![[:alnum:]!?_:]!)):[[:alnum:]!?_:-]+</string>
			<key>name</key>
			<string>string.literal.symbol.ioke</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>#/</string>
			<key>end</key>
			<string>/[oxpniums]*</string>
			<key>name</key>
			<string>string.regexp.ioke</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#text_literal_escapes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_source</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>#r\[</string>
			<key>end</key>
			<string>\][oxpniums]*</string>
			<key>name</key>
			<string>string.regexp.ioke</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#text_literal_escapes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_source</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>:"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.literal.symbol.ioke</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#text_literal_escapes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_source</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.ioke</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#text_literal_escapes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_source</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>#\[</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>string.quoted.double.ioke</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#text_literal_escapes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_source</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>((?&lt;![[:alnum:]!?_:])|(?&lt;![[:alnum:]!?_:]!))it(?![[:alnum:]!?_:])</string>
			<key>name</key>
			<string>entity.standout-names.ioke</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#{</string>
			<key>name</key>
			<string>punctuation.set-literal-start.ioke</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\`\`|\`|''|'|\.|\,|@|@@|\[|\]|\(|\))</string>
			<key>name</key>
			<string>punctuation.ioke</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[[:alnum:]_][[:alnum:]!?_:$]*[[:alnum:]!?_:]</string>
			<key>name</key>
			<string>source.identifier.ioke</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>assignments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=[[:space:]])[^[:space:].]+=[[:space:]]*=[[:space:]](fn|fnx|method|macro|lecro|syntax|dmacro|dlecro|dlecrox|dsyntax)</string>
					<key>name</key>
					<string>variable.assignment.function.ioke</string>
				</dict>
			</array>
		</dict>
		<key>embedded_source</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.ioke</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>source.embedded.empty.ioke</string>
						</dict>
					</dict>
					<key>match</key>
					<string>#\{(\})</string>
					<key>name</key>
					<string>source.embedded.ioke</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>#\{</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.ioke</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>source.embedded.ioke</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#nest_curly_and_self</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>((?&lt;![[:alnum:]!?_:])|(?&lt;![[:alnum:]!?_:]!))(mimic|self|use|true|false|nil)(?![[:alnum:]!?_:])</string>
					<key>name</key>
					<string>keyword.ioke</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((?&lt;![[:alnum:]!?_:])|(?&lt;![[:alnum:]!?_:]!))(return|break|continue|unless|true|false|nil)(?![[:alnum:]!?_:])</string>
					<key>name</key>
					<string>keyword.control.ioke</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(&amp;&amp;&gt;&gt;|\|\|&gt;&gt;|\*\*&gt;&gt;|\.\.\.|===|\*\*&gt;|\*\*=|&amp;&amp;&gt;|&amp;&amp;=|\|\|&gt;|\|\|=|\-&gt;&gt;|\+&gt;&gt;|!&gt;&gt;|&lt;&gt;&gt;&gt;|&lt;&gt;&gt;|&amp;&gt;&gt;|%&gt;&gt;|#&gt;&gt;|@&gt;&gt;|/&gt;&gt;|\*&gt;&gt;|\?&gt;&gt;|\|&gt;&gt;|\^&gt;&gt;|~&gt;&gt;|\$&gt;&gt;|=&gt;&gt;|&lt;&lt;=|&gt;&gt;=|&lt;=&gt;|&lt;\-&gt;|=~|!~|=&gt;|\+\+|\-\-|&lt;=|&gt;=|==|!=|&amp;&amp;|\.\.|\+=|\-=|\*=|\/=|%=|&amp;=|\^=|\|=|&lt;\-|\+&gt;|!&gt;|&lt;&gt;|&amp;&gt;|%&gt;|#&gt;|\@&gt;|\/&gt;|\*&gt;|\?&gt;|\|&gt;|\^&gt;|~&gt;|\$&gt;|&lt;\-&gt;|\-&gt;|&lt;&lt;|&gt;&gt;|\*\*|\?\||\?&amp;|\|\||&gt;|&lt;|\*|\/|%|\+|\-|&amp;|\^|\||=|\$|!|~|\?|#)</string>
					<key>name</key>
					<string>keyword.operator.ioke</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((?&lt;![[:alnum:]!?_:])|(?&lt;![[:alnum:]!?_:]!))(nand|and|nor|xor|or)(?![[:alnum:]!?_:])</string>
					<key>name</key>
					<string>keyword.operator.boolean.ioke</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((?&lt;![[:alnum:]!?_:])|(?&lt;![[:alnum:]!?_:]!))(Base|Call|Condition|DateTime|DefaultBehavior|DefaultMacro|DefaultMethod|DefaultSyntax|Dict|FileSystem|Ground|Handler|IO|JavaMethod|LexicalBlock|LexicalMacro|List|Message|Method|Mixins|Number|Number Decimal|Number Integer|Number Rational|Number Real|Origin|Pair|Range|Regexp|Rescue|Restart|Runtime|Set|Symbol|System|Text)(?![[:alnum:]!?_:])</string>
					<key>name</key>
					<string>keyword.prototype-names.ioke</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((^)|(?&lt;![[:alnum:]!?_:])|(?&lt;![[:alnum:]!?_:]!))(fn|fnx|method|macro|lecro|syntax|dmacro|dlecro|dlecrox|dsyntax)(?![[:alnum:]!?_:])</string>
					<key>name</key>
					<string>keyword.function.ioke</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((?&lt;![[:alnum:]!?_:])|(?&lt;![[:alnum:]!?_:]!))(print|println|cell\?|cell|keyword|documentation|if|unless|while|until|loop|for|for:set|for:dict|bind|rescue|handle|restart|asText|inspect|notice|do|call|list|dict|set|with|kind)(?![[:alnum:]!?_:])</string>
					<key>name</key>
					<string>keyword.cell-names.ioke</string>
				</dict>
			</array>
		</dict>
		<key>kinds</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>((?&lt;![[:alnum:]!?_:])|(?&lt;![[:alnum:]!?_:]!))[A-Z][[:alnum:]!?_:-]*(?![[:alnum:]!?_:])</string>
					<key>name</key>
					<string>constant.kind.ioke</string>
				</dict>
			</array>
		</dict>
		<key>meta_parens</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>include</key>
					<string>#meta_parens</string>
					<key>name</key>
					<string>meta.parens.ioke</string>
				</dict>
			</array>
		</dict>
		<key>nest_curly_and_self</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.scope.ioke</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#nest_curly_and_self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>text_literal_escapes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\\b|\\e|\\t|\\n|\\f|\\r|\\"|\\\\|\\#|\\\Z|\\u[[:xdigit:]][[:xdigit:]][[:xdigit:]][[:xdigit:]]|\\[0-3]?[0-7]?[0-7],[[:space:]]+\\[0-3]?[0-7]?[0-7],[[:space:]]+\\[0-3]?[0-7]?[0-7]|\\[0-3]?[0-7]?[0-7],[[:space:]]+\\[0-3]?[0-7]?[0-7]|\\[0-3]?[0-7]?[0-7])</string>
					<key>name</key>
					<string>constant.character.escape.ioke</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ioke</string>
	<key>uuid</key>
	<string>EC751C80-9E93-44B4-AFF3-EF4FF8346C90</string>
</dict>
</plist>
