<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ik</string>
	</array>
	<key>name</key>
	<string>Ioke</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b("Base|DefaultBehavior|Ground|Origin|System|Runtime|Text|Number|Method|DefaultMethod|JavaMethod|Mixins|Restart|List|Dict")\b</string>
			<key>name</key>
			<string>keyword.prototype-names.ioke</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b("print|println|cell|documentation|while|until|asText|inspect|loop|bind|restart|do|true?|false?|nil?|call|list|dict|empty?|with")\b</string>
			<key>name</key>
			<string>keyword.cell-names.ioke</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\.\.\.|=&gt;|\+\+|\-\-|\*|/|%|\+|\-|&lt;&lt;|&gt;&gt;|&gt;|&lt;|&lt;=|&gt;=|&lt;=&gt;|==|!=|&amp;|\^|\||&amp;&amp;|\|\||\.\.|=|\+=|\-=|\*=|/=|%=|&amp;=|\^=|\|=|&lt;&lt;=|&gt;&gt;=|&lt;\-|&lt;\-&gt;|\-&gt;)</string>
			<key>name</key>
			<string>keyword.operator.ioke</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ioke</string>
	<key>uuid</key>
	<string>EC751C80-9E93-44B4-AFF3-EF4FF8346C90</string>
</dict>
</plist>
